services:
  - type: web
    name: min-finanspanel
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_CLIENT_ID
        fromSecret: google-client-id
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: google-client-secret